require "bundler/setup"
require "bundler/gem_tasks"
require "bump/tasks"

Bundler::GemHelper.install_tasks

task default: %i[run]

task :run do
  exec "./bin/iris"
end

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

# require "standard/rake"
