# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME='tool-markdown'

Vagrant.configure("2") do |config|
  config.vm.define HOSTNAME do |i|
    # Configure BOX
    i.vm.box = "generic/opensuse15"

    # Configure VM
    i.vm.hostname = HOSTNAME
    # i.vm.network "public_network", bridge: [ "eth0" ]
    # i.vm.network "public_network", bridge: [ "wlan0" ]
    # i.vm.network :forwarded_port, guest: 22, host: 2222
    i.vm.network :forwarded_port, guest: 22, host: 3122
    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", path: 'install.sh'

    # Configure VIRTUALBOX
    i.vm.provider "virtualbox" do |v|
      v.name = HOSTNAME
      v.memory = 2048
    end
  end
end
