#!/usr/bin/env ruby

require 'telegram/bot'
require 'pry-byebug'
require_relative 'lib/ai'

# token:
# 1. Write your TOKEN value into "token" variable or
# 2. Create a local file "private.token" with your TOKEN value inside
token = `cat private.token`.strip
bot_username = '@dvarrui_bot'

custom = Custom.new(token: token, bot_username: bot_username)

puts "[INFO] Running bot #{$0}..."

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    puts " => #{message.text}"
    hello = Regexp.new(action[:hello][:rex])
    bye = Regexp.new(action[:bye][:rex])

    case message.text
    when hello
      text = action[:hello][:text]
    when bye
      text = action[:hello][:text]
      wanna_exit = true
    end
    bot.api.send_message(chat_id: message.chat.id, text: text)
    exit 0 if wanna_exit
  end
end
