
require_relative 'tasks/build'
require_relative 'tasks/install'
require_relative 'tasks/push'

desc 'Default: check'
task :default do
  Rake::Task['install:check'].invoke
end

desc 'Rake help'
task :help do
  system('rake -T')
end

desc 'Remove temp files'
task :clean do
  system("rm -r html/*")
end
